development:
  adapter: postgresql
  encoding: unicode
  database: demo
  pool: 5
  host: localhost
  username: postgres
  password: 12345678

test:
  adapter: postgresql
  encoding: unicode
  database: demo_test
  pool: 5
  host: localhost
  username: postgres
  password: 12345678